spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: voot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    
